messages:
  hello: Hello BITCHES!
database:
  driverClass: com.mysql.jdbc.Driver
  user: dropwizard
  password: wizard
  url: jdbc:mysql://192.168.1.205/dropwizard
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "SELECT * FROM PERSON"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute