database:
  driverClass: com.mysql.jdbc.Driver
  user: dropwizard
  password: password
  url: jdbc:mysql://localhost/dropwizard
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "SELECT * FROM PEOPLE LIMIT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
